### ISSUE TITLE
[cinder-csi-plugin] Example file is outdated

### ISSUE THREAD

**Issue by eumel8** [kubernetes/cloud-provider-openstack#1117]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

The example of Cinder CSI snapshot in [1] is outdated. Parameters and API endpoints are changed and won't work in 1.18.

[1] https://github.com/kubernetes/cloud-provider-openstack/blob/master/examples/cinder-csi-plugin/snapshot/snapshotcreate.yaml

**What you expected to happen**:

 I referenced to [2] which gives me a valid example. Maybe refer to the common repo or copy the content periodically from there.

[2] https://github.com/kubernetes-csi/external-snapshotter/blob/master/examples/kubernetes/snapshot.yaml

**How to reproduce it**:

error: no matches for kind "VolumeSnapshot" in version "snapshot.storage.k8s.io/v1alpha1"

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: 1.18
- OpenStack version: unknown
- Others:

**Comment by ramineni** [comment]
@eumel8 yes, this is valid bug , with updated provisoner version to 1.6.0 , v1alpha1 is no longer supported . Its supported only till 1.4.0 . I suppose we need snapshotter v2.0.0 to use v1beta1.

@jichenjc will you be able to check this?

**Comment by jichenjc** [comment]
ok, seems we have to faster https://github.com/kubernetes/cloud-provider-openstack/pull/974
I am blocked by https://github.com/kubernetes/cloud-provider-openstack/pull/997 because not enough time to check and less expertise in this area 

so maybe without CI e2e let's check manually with https://github.com/kubernetes/cloud-provider-openstack/pull/974 then it should fix the problem

**Comment by ramineni** [comment]
@jichenjc great , sounds like a plan . I can check the e2e part sometime this week .
Between , it would be good if you could manually test the 2.0.0 version upgrade with existing example files and get the PR ready .

**Comment by jichenjc** [comment]
The PR is merged, maybe we need wait for CI e2e test then close this issue

**Comment by ramineni** [comment]
@jichenjc we can close this , as the issue mentioned in description should be fixed by #974 
@eumel8 pls reopen incase you still face the issue. Should be available in latest image or 1.19 release version which we would be doing in couple of days.

**Comment by eumel8** [comment]
@ramineni thanks for the work. I'm now in 1.19 and endpoints are correct, but I've got the following error:

```
I1206 23:06:27.130534       1 snapshot_controller.go:292] createSnapshotWrapper: CreateSnapshot for content snapcontent-a9a5c55e-781b-4024-acd2-9ebc7961d715 returned error: rpc error: code = Internal desc = CreateSnapshot failed with error Bad request with: [POST https://evs.eu-de.otc.t-systems.com/v3/xxxxxx/snapshots], error message: {"badRequest": {"message": "Invalid volume: Volume e129824a-16fa-486d-a8c7-482945a626ff status must be available, but current status is: in-use.", "code": 400}}
```

I think it's cloud-specific. [Documentation](https://docs.otc.t-systems.com/en-us/api/evs/evs_04_3056.html) says, `force: true` would be required to snapshot EVS in use state. The field is optional in [Cinder V3 API](https://docs.openstack.org/api-ref/block-storage/v3/?expanded=create-a-snapshot-detail#volume-snapshots-snapshots)

**Comment by jichenjc** [comment]
I think it depends on your use case, if you expect to snapshot for in-use volume you should enable the field .
