### ISSUE TITLE
Can't resize volumes migrated after CSI migration

### ISSUE THREAD

**Issue by thcdrt** [kubernetes/cloud-provider-openstack#874]
Hello,

I don't know if I should open an issue here or at the csi-resizer repo.

**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**The binaries affected**:
- [ ] cinder-csi-plugin

**What happened**:
I tried to resize a volume created by Intree cinder plugin after migration from intree cinder plugin to CSI.

**What you expected to happen**:
The volume to be resized

**How to reproduce it**:
I created a PVC on my Kubernetes cluster using cinder intree provider. Then I migrated to CSI using the [doc](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/migrate-to-ccm-with-csimigration.md).
Then I tried to resize the PVC: 
`kubectl patch pvc mysql-pv-claim -p '{ "spec": { "resources": { "requests": { "storage": "6Gi" }}}}'
`

**Anything else we need to know?**:
When creating a volume once the migration is done I can resize volume without any problem.
The bug only applies on volumes created by cinder intree plugin.

Events on the PVC:
```  
Normal   ExternalExpanding  15m (x22 over 87m)  volume_expand  CSI migration enabled for cinder.csi.openstack.org; waiting for external resizer to expand the pvc
Warning  ExternalExpanding  15m (x22 over 87m)  volume_expand  error getting CSI driver name for pvc default/mysql-pv-claim, with error could not find CSI Driver name for plugin cinder.csi.openstack.org
```

Logs of csi-resizer:
```
I1212 11:28:30.505522       1 controller.go:211] Started PVC processing "default/mysql-pv-claim"
I1212 11:28:30.505751       1 csi_resizer.go:127] PV pvc-a8e0d3ff-1cce-11ea-ba01-ea30067a6eb6 is not a CSI volume, skip it
I1212 11:28:30.505765       1 controller.go:269] Resizer "cinder.csi.openstack.org" doesn't support PV "pvc-a8e0d3ff-1cce-11ea-ba01-ea30067a6eb6"
I1212 11:28:30.505779       1 controller.go:245] No need to resize PV "pvc-a8e0d3ff-1cce-11ea-ba01-ea30067a6eb6"
```

**Environment**:
- Kubernetes version: 1.15
- Csi-resizer: 0.2.0:
- Cinder-csi-plugin Sha256: a065f58ac06f7359f97f2c06b1e97d39c795447bb80e20b7f5216e66effa620e

Thank you in advance for your help

**Comment by ramineni** [comment]
@thcdrt Looks like pvc is not being identified as migrated intree volume , Could you paste the o/p of  `kubectl describe pvc` and `kubectl describe pv` 
Ideally for migrated PV this annotation `volume.kubernetes.io/storage-resizer` should be set to csi driver name.

**Comment by thcdrt** [comment]
Hello @ramineni , thanks for your answer.

`> kubectl describe pvc

`

`> kubectl describe pv

`

Who should set the annotation volume.kubernetes.io/storage-resizer to the PV ?

I use the 1.16 cinder-csi-plugin version. As said, resizing volumes created with CSI is working like a charm. Only migrated volumes can't be resized, so I don't think it comes from cinder-csi-plugin version.

**Comment by thcdrt** [comment]
I added manually the annotation  **pv.kubernetes.io/provisioned-by**, but this is still not working with the same error message.

**Comment by ramineni** [comment]
@thcdrt yes, sorry its a PVC annotation. It should be automatically set by intree resize controller.
I see that you are getting the below error , might be reason its returning before setting the above annotation. 
` Warning  ExternalExpanding  15m (x22 over 87m)  volume_expand  error getting CSI driver name for pvc default/mysql-pv-claim, with error could not find CSI Driver name for plugin cinder.csi.openstack.org`

From the above error , looks like its trying to retrieve the mapping between intree to CSI , but as its already set to csi driver name 'cinder.csi.openstack.org'  so its failing . 
Could you try again without manually changing anything to csi driver name in PV, that should solve the issue.

**Comment by thcdrt** [comment]
Hello @ramineni ,
I tried without modifying the annotation too, but still not working:
```
kubectl describe pvc
Name:          mysql-pv-claim
Namespace:     default
StorageClass:  cinder-high-speed
Status:        Bound
Volume:        pvc-feb15643-1fe4-11ea-9d70-d6335d876b32
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"mysql-pv-claim","namespace":"default"},"spec":{"acc...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/cinder
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      2Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    mysql-7b9b7999d8-bpblt
Events:
  Type     Reason                 Age                 From                         Message
  ----     ------                 ----                ----                         -------
  Normal   ProvisioningSucceeded  12m                 persistentvolume-controller  Successfully provisioned volume pvc-feb15643-1fe4-11ea-9d70-d6335d876b32 using kubernetes.io/cinder
  Warning  ExternalExpanding      18s (x12 over 28s)  volume_expand                error getting CSI driver name for pvc default/mysql-pv-claim, with error could not find CSI Driver name for plugin cinder.csi.openstack.org
  Normal   ExternalExpanding      8s (x13 over 28s)   volume_expand                CSI migration enabled for cinder.csi.openstack.org; waiting for external resizer to expand the pvc
```

```
kubectl describe pv
Name:              pvc-feb15643-1fe4-11ea-9d70-d6335d876b32
Labels:            failure-domain.beta.kubernetes.io/region=GRA5
                   failure-domain.beta.kubernetes.io/zone=nova
Annotations:       kubernetes.io/createdby: cinder-dynamic-provisioner
                   pv.kubernetes.io/bound-by-controller: yes
                   pv.kubernetes.io/provisioned-by: kubernetes.io/cinder
Finalizers:        [kubernetes.io/pv-protection external-attacher/cinder-csi-openstack-org]
StorageClass:      cinder-high-speed
Status:            Bound
Claim:             default/mysql-pv-claim
Reclaim Policy:    Delete
Access Modes:      RWO
VolumeMode:        Filesystem
Capacity:          2Gi
Node Affinity:     
  Required Terms:  
    Term 0:        failure-domain.beta.kubernetes.io/region in [GRA5]
                   failure-domain.beta.kubernetes.io/zone in [nova]
Message:           
Source:
    Type:       Cinder (a Persistent Disk resource in OpenStack)
    VolumeID:   b8312d18-2463-4035-9144-53ab4811546a
    FSType:     
    ReadOnly:   false
    SecretRef:  nil
Events:         <none>
```

**Comment by thcdrt** [comment]
Indeed, I just tried to not changer the storageclass and it's now working. Thanks for the debugging ! Maybe it could be added in the migration doc !

Thomas
